import { Inter } from "next/font/google";
import "./globals.css";
import localFont from '@next/font/local'

const sukhumvitText = localFont({src:'../../public/fonts/SukhumvitSet-Text.ttf', variable: '--font-sukhumvitText'})
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${sukhumvitText.variable} font-sans`}>{children}</body>
    </html>
  );
}
